import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { RunCommand, ToolResult } from "./types.js";
import { errorMessage, failure, success } from "./types.js";
import { runCommand as defaultRunCommand } from "./runner.js";

export const devAgentSchema = {
  type: "object",
  properties: {
    action: { type: "string", enum: ["scaffold", "run_command"] },
    target_dir: { type: "string" },
    project_name: { type: "string" },
    template: { type: "string", enum: ["node-cli", "python-cli"] },
    command: { type: "array", items: { type: "string" } },
    timeout: { type: "number" },
  },
};

function cleanName(raw: string): string {
  return (raw || "stark_project").replace(/[^\w-]/g, "_").slice(0, 80);
}

async function scaffoldNodeCli(dir: string, projectName: string) {
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "package.json"), JSON.stringify({ name: projectName, version: "0.1.0", type: "module", scripts: { start: "node src/index.js" } }, null, 2) + "\n");
  await mkdir(join(dir, "src"), { recursive: true });
  await writeFile(join(dir, "src", "index.js"), "console.log('STARK-AI project ready');\n");
  await writeFile(join(dir, "README.md"), `# ${projectName}\n\nDeterministic scaffold generated by mcp-dev.\n`);
}

async function scaffoldPythonCli(dir: string, projectName: string) {
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "main.py"), "def main():\n    print('STARK-AI project ready')\n\nif __name__ == '__main__':\n    main()\n");
  await writeFile(join(dir, "README.md"), `# ${projectName}\n\nDeterministic Python scaffold generated by mcp-dev.\n`);
}

export function createDevAgent(deps: { runCommand?: RunCommand } = {}) {
  const runCommand = deps.runCommand ?? defaultRunCommand;
  return async (args: Record<string, unknown>): Promise<ToolResult> => {
    const action = String(args.action ?? "scaffold").toLowerCase();
    const targetDir = String(args.target_dir ?? "").trim();
    if (!targetDir) return failure("MISSING_TARGET_DIR", "Provide target_dir.");
    try {
      if (action === "run_command") {
        const command = Array.isArray(args.command) ? args.command.map(String).filter(Boolean) : [];
        if (command.length === 0) return failure("MISSING_COMMAND", "Provide command array.");
        const result = await runCommand(command, targetDir, Math.max(1000, Math.min(120_000, Number(args.timeout ?? 30) * 1000)));
        return success({ cwd: targetDir, command, exitCode: result.code, stdout: result.stdout, stderr: result.stderr });
      }
      if (action !== "scaffold") return failure("UNKNOWN_ACTION", `Unknown dev_agent action: ${action}`);
      const projectName = cleanName(String(args.project_name ?? "stark_project"));
      const template = String(args.template ?? "node-cli");
      const projectDir = join(targetDir, projectName);
      if (template === "python-cli") await scaffoldPythonCli(projectDir, projectName);
      else await scaffoldNodeCli(projectDir, projectName);
      return success({ projectName, template, projectDir, note: "LLM planning/writing was dropped; deterministic templates only." });
    } catch (error) {
      return failure("DEV_AGENT_FAILED", "dev_agent failed.", errorMessage(error));
    }
  };
}
